### ISSUE TITLE
tabular data/ noisy instances/ new datasets

### ISSUE THREAD

**Issue by nazaretl** [wangjksjtu/rl-perturbed-reward#1]
Hi,
thanks for sharing your implementation. I have some questions about it:

1.	Does it also work on tabular data?
2.	Is the code tailored to the datasets used in the paper or can one apply it to any data?
3.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by wangjksjtu** [comment]
Hi @nazaretl, Thanks for the interest in our work!

1. Yeah, the theory is actually drived in on the tabular setting. It should work on tabular data ;)
2. Not sure yet, in general this idea is agnostic to the dataset. However, on some setting, it might be very hard to recover from the failure cases especially the noise rate is large (see noise variance tradeoff in the paper). Moreover, in our analysis, the noise should be discrete which might not be the exact setting in the real world. While we have seen some effectiveness in continuous noise, it is not guaranteed to work to any data.
3. In our experiments, we add the noise to the observed reward for every episode. If you want to take a look at those state-action pairs, maybe you can change in this [function](https://github.com/wangjksjtu/rl-perturbed-reward/blob/master/gym-control/noise_estimator.py#L106) to record them.

Please let me know if you have any other questions ;)

**Comment by nazaretl** [comment]
many thanks for the response!
